# Generated by Django 5.0.9 on 2024-10-23 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='O texto deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù\\s]+$')], verbose_name='Cargo'),
        ),
    ]
