# Generated by Django 5.0.9 on 2024-10-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
