# Generated by Django 5.0.9 on 2024-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('limiar_minimo', models.IntegerField()),
                ('limiar_maximo', models.IntegerField()),
            ],
        ),
    ]
