# Generated by Django 5.0.9 on 2024-09-29 01:59

import django.core.validators
import gerenciamento_laboratorial.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11), gerenciamento_laboratorial.users.validators.valid_cpf_validator], verbose_name='CPF'),
        ),
    ]
