# Generated by Django 5.0.9 on 2024-09-29 04:30

import django.db.models.deletion
import gerenciamento_laboratorial.users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField(blank=True, null=True, validators=[gerenciamento_laboratorial.users.validators.maior_de_idade_validator], verbose_name='Data de Nascimento')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
