# Generated by Django 5.0.9 on 2024-09-29 20:21

import gerenciamento_laboratorial.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[gerenciamento_laboratorial.users.validators.maior_de_idade_validator], verbose_name='Data de Nascimento'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
