# Generated by Django 5.0.9 on 2024-10-26 15:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0002_paciente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(validators=[django.core.validators.RegexValidator(message="O texto deve conter apenas letras, espaços, vírgulas, traços('-') e números.", regex='^[a-zá-ùA-ZÁ-Ù0-9\\s,-]+$')])),
                ('resultado', models.TextField(validators=[django.core.validators.RegexValidator(message="O texto deve conter apenas letras, espaços, vírgulas, traços('-') e números.", regex='^[a-zá-ùA-ZÁ-Ù0-9\\s,-]+$')])),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('AGENDAMENTO', 'Esperando confirmação dos técnicos'), ('AGENDADO', 'Exame agendado'), ('CANCELAMENTO', 'Cancelamento solicitado')], default='AGENDAMENTO', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='paciente.paciente')),
            ],
        ),
    ]
