# Generated by Django 5.0.9 on 2024-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_atendimento', models.DateField(verbose_name='Horário do atendimento')),
                ('limite_fichas', models.PositiveIntegerField(verbose_name='Limite de fichas disponíveis')),
            ],
        ),
    ]
