# Generated by Django 5.0.9 on 2024-10-26 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horario_atendimento', models.DateTimeField(verbose_name='Horário do atendimento')),
                ('limite_fichas', models.PositiveIntegerField(verbose_name='Limite de fichas disponíveis')),
            ],
        ),
    ]
