# Generated by Django 5.0.9 on 2024-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='horario_atendimento',
            field=models.DateTimeField(verbose_name='Horário do atendimento'),
        ),
    ]
