# Generated by Django 5.0.9 on 2024-10-22 22:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('alergias', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='O texto deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù\\s]+$')])),
                ('comorbidades', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='O texto deve conter apenas letras', regex='^[a-zá-ùA-ZÁ-Ù\\s]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
