# Generated by Django 5.0.9 on 2024-10-22 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message="O texto deve conter apenas letras, espaços, vírgulas, traços('-') e números.", regex='^[a-zá-ùA-ZÁ-Ù0-9\\s,-]+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comorbidades',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message="O texto deve conter apenas letras, espaços, vírgulas, traços('-') e números.", regex='^[a-zá-ùA-ZÁ-Ù0-9\\s,-]+$')]),
        ),
    ]
